name: Nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-flake:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run flake checks
      run: |
        nix flake check \
          --option allow-import-from-derivation false
    - name: Check Darwin and Home Manager systems
      run: |
        nix eval --raw -f .github/check-hosts.nix
